name: show-directory
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Setup
        id: S01
        run: make setup
      
      - name: Test
        id: T01
        run: make test

      - name: Linter
        id: L01
        run: make lint
